#!/usr/bin/env node
// bnbulls — deal the 501 names and write them where the deploy scripts read them.
//
//   node scripts/gen-names.mjs            # -> deployments/names.json
//   node scripts/gen-names.mjs --check    # regenerate and diff, write nothing
//
// ─────────────────────────────────────────────────────────────────────────────
// ⚠ THE ONE THING THAT MATTERS IN THIS FILE
// ─────────────────────────────────────────────────────────────────────────────
// `DECISIONS.md §9`: names are DEALT, not drawn — the peerage rank in a name IS
// the rarity ladder. `Sid Calverley` is a commoner, `His Grace the Duke of
// Blandford` is a legendary. So a name is only correct if the tier it was dealt
// against is the tier the CHAIN thinks that token has.
//
// The generator's own `assignBands()` and the `Bulls` constructor's
// `_initializeRarity()` were DIFFERENT ALGORITHMS:
//
//   assignBands()        LCG(MASTER_SEED), shuffles the ID list, slices it
//   _initializeRarity()  Xorshift128+(masterSeed ^ "SHUFF"), shuffles the TIER
//                        array in place
//
// They did not agree — 377 of the 500 tokens differed — and nothing on chain
// would ever have told you. A legendary bull would carry a farmhand's name and
// a common bull would be introduced as a duke, permanently, because
// `namesCommitment` is immutable and `freezeNames()` is one-way.
//
// ⚠ THERE IS NOW EXACTLY ONE IMPLEMENTATION OF THE CHAIN'S SHUFFLE, and it
// lives in `generator/bull.mjs` as `chainTiers()` / `chainBandMap()`. This
// script used to carry its own private copy of the Xorshift port; two copies
// of a shuffle that must agree with a contract is the same bug wearing a
// different hat, so the copy is gone and this imports the real one. The art
// (`generator/build.mjs`), the site (`frontend/src/lib/art/collection.ts`) and
// this name dealer therefore cannot drift apart — they are the same function.
//
// `assignBands()` is DELETED. `Verify.s.sol` checks every one of the 501
// published names against this table, `script/Names.s.sol:PrintNamesCommitment`
// proves the port against a real `Bulls` constructor, and
// `cd frontend && npm run verify:rarity` gates all of it on every run.
//
// ─────────────────────────────────────────────────────────────────────────────
// No npm dependencies on purpose. The commitment is computed in SOLIDITY
// (`BnbullsConfig.namesCommitment`), so there is exactly one keccak
// implementation in the loop and nothing here needs `ethers` installed.

import { writeFileSync, mkdirSync, existsSync, readFileSync } from "node:fs";
import { assignNames, chainTiers, BANDS, BAND_COUNTS, SUPPLY, KING_ID, KING_NAME,
         MASTER_SEED } from "../generator/bull.mjs";

// ── Deal ────────────────────────────────────────────────────────────────────

const masterSeed = process.env.MASTER_SEED
  ? BigInt(process.env.MASTER_SEED)
  : BigInt(MASTER_SEED);

// `chainTiers()` reproduces `initialRarityHash`: the table as it is the instant
// the constructor finishes, BEFORE any `_skipRareForDev` swap can mutate it.
// That is the right snapshot to deal names against, because it is the one the
// commitment covers.
const rarity = chainTiers(masterSeed);

// Sanity: the counts must still be 200/130/90/50/30 after the shuffle.
const counts = [0, 0, 0, 0, 0];
for (const t of rarity) counts[t]++;
BANDS.forEach((band, i) => {
  if (counts[i] !== BAND_COUNTS[band]) {
    throw new Error(`tier ${band}: shuffled count ${counts[i]} != ${BAND_COUNTS[band]}`);
  }
});

// The band map `assignNames` expects: { tokenId -> tier name }.
const bandMap = {};
for (let id = 1; id <= SUPPLY; id++) bandMap[id] = BANDS[rarity[id - 1]];

const dealt = assignNames(bandMap);

// 501 names, 501 unique, in token-id order. `assignNames` throws rather than
// shipping a duplicate, but a second check here costs nothing and this table
// is immutable once `freezeNames()` runs.
const names = [];
for (let id = 1; id <= SUPPLY; id++) {
  if (!dealt[id]) throw new Error(`no name dealt for token ${id}`);
  names.push(dealt[id]);
}
names.push(dealt[KING_ID]);
if (names.length !== 501) throw new Error(`expected 501 names, got ${names.length}`);
if (names[500] !== KING_NAME) throw new Error(`king #501 must be "${KING_NAME}"`);
const unique = new Set(names);
if (unique.size !== 501) throw new Error(`names collide: ${501 - unique.size} duplicates`);

// ── Write ───────────────────────────────────────────────────────────────────

if (!existsSync("deployments")) mkdirSync("deployments", { recursive: true });

const namesJson = {
  _comment:
    "DEALT name table (DECISIONS.md 9). Generated by scripts/gen-names.mjs against " +
    "the CHAIN's rarity shuffle, not the generator's. Index 0 is token #1; index 500 " +
    "is the king #501. The commitment is keccak256(abi.encode(string[501])), computed " +
    "in Solidity by BnbullsConfig.namesCommitment so there is one implementation.",
  masterSeed: masterSeed.toString(),
  masterSeedHex: "0x" + masterSeed.toString(16),
  count: names.length,
  names,
};

const rarityJson = {
  _comment:
    "The CHAIN's rarity table, re-derived off-chain from masterSeed by porting " +
    "Xorshift128+ and Bulls._initializeRarity(). Matches initialRarityHash, i.e. the " +
    "table before any dev-mint skip-rare swap. tiers[tokenId-1] in 0..4. " +
    "There is ONE implementation of the shuffle - generator/bull.mjs chainTiers() - " +
    "and the art, the site and this dealer all call it. This file is the committed " +
    "copy that generator/build.mjs and frontend `npm run verify:rarity` check against.",
  masterSeed: masterSeed.toString(),
  tiers: rarity,
  tierNames: BANDS,
  counts: Object.fromEntries(BANDS.map((b, i) => [b, counts[i]])),
};

const check = process.argv.includes("--check");
if (check) {
  const prev = JSON.parse(readFileSync("deployments/names.json", "utf8"));
  const same =
    prev.count === namesJson.count &&
    prev.masterSeed === namesJson.masterSeed &&
    prev.names.every((n, i) => n === names[i]);
  console.log(same ? "names.json is up to date" : "NAMES.JSON IS STALE - regenerate");
  process.exit(same ? 0 : 1);
}

writeFileSync("deployments/names.json", JSON.stringify(namesJson, null, 2) + "\n");
writeFileSync("deployments/rarity.json", JSON.stringify(rarityJson, null, 2) + "\n");

// ── Report ──────────────────────────────────────────────────────────────────

console.log(`masterSeed  ${namesJson.masterSeedHex} (${masterSeed})`);
console.log(`names       ${names.length}, ${unique.size} unique`);
BANDS.forEach((band, i) => {
  const first = names.findIndex((_, idx) => idx < SUPPLY && rarity[idx] === i);
  console.log(`  ${band.padEnd(10)} ${String(counts[i]).padStart(3)}  e.g. #${first + 1} ${names[first]}`);
});
console.log(`  king        1  #${KING_ID} ${names[500]}`);
console.log("");
console.log("wrote deployments/names.json");
console.log("wrote deployments/rarity.json");
console.log("");
console.log("The commitment goes into the Bulls constructor and is IMMUTABLE.");
console.log("Print it with:  forge script script/Names.s.sol:PrintNamesCommitment");
console.log("");
console.log("If the seed changed, the art and the pinned hashes changed with it:");
console.log("  node generator/build.mjs                       re-render the sheets");
console.log("  cd frontend && npm run verify:rarity           re-gate the whole table");
console.log("  FOUNDRY_SCRIPT=generator/probe forge script \\");
console.log("    generator/probe/ChainTableProbe.s.sol:ChainTableProbe");
console.log("                                                re-pin against the contract");
